# Generated by Django 4.2.6 on 2023-11-10 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('promotion_type', models.CharField(choices=[('no promotion', 'Nopromotion'), ('breakfast', 'Breakfast'), ('discount in daily', 'Discountindaily'), ('extended stay discount', 'Extendedstaydiscount'), ('discount', 'Discount')], default='no promotion')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('discount_percentage', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
