# Generated by Django 4.2.6 on 2023-11-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_promotions'),
        ('users', '0002_user_is_administrator_user_is_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_rooms',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='rooms.room'),
        ),
    ]
