# Generated by Django 4.2.6 on 2023-11-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_favorite_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_administrator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('US', 'User'), ('EM', 'Employee'), ('MA', 'Manager')], default='US'),
        ),
    ]
