# Generated by Django 4.2.6 on 2023-11-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_administrator_remove_user_is_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_type',
            new_name='type_user',
        ),
    ]
