# Generated by Django 4.2.6 on 2023-11-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='promotions.promotion'),
        ),
    ]
